
# Setup
title:               Open Drupal
# email:               example@gmail.com
tagline:             An open curriculum of Drupal course materials
url:                 "https://opendrupal.org" # insert your site's URL
baseurl:             "/"

# About/contact
author: # you can edit these to be your personal details
  name:              Crispin Read
  url:               https://twitter.com/crispin_read
  email:

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics:
google_tag_manager:
# Bing services
bing_verification:

# Social
github_username: opendrupal
# twitter_username: 3rdwave_themes
# instagram_username: kevin/
# facebook: 3rdwavethemes/
# linkedin_username: xiaoying
# dribbble_username: Xiaoying

# Custom vars
version:             1.0.1
github:
  repo:              https://github.com/OpenDrupal/opendrupal.org-site

# Gems - Dependencies for this theme
gems:
  # None currently

# Build settings
markdown:     kramdown
permalink:    pretty

widgets:
  - title: About
    url: /about
  - title: Materials
    url: /materials
  - title: Contribute
    url: /contribute
  - title: Contact
    url: /contact
